version: 2
jobs:
  build:
    working_directory: ~/app-name
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-lint
          command: yarn lint
      - deploy:
          name: S3 Bucket Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync dist s3://lineupsdotcom/ --delete
            else
              echo "Non master branch not deploying to s3."
            fi
      - run:
          name: Cloudfront Invalidation
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws cloudfront create-invalidation --cli-input-json "{\"DistributionId\":\"E2CAIO4776LUFJ\",\"InvalidationBatch\":{\"Paths\":{\"Quantity\":1,\"Items\":[\"/*\"]},\"CallerReference\":\"$(date +%s)\"}}"
            else
              echo "Non master branch not invaliding cloudfront distribution."
            fi
